

name: Python CI 

# In order to Trigger a Workflow we  need to define some events
# Triggers the Workflow On Any Push to the main branch or pull request


# using On We trigger the Workflow 
on:
    push:
        branches:
            -main 

    pull_request:
          branches:
             -main
             # more branches add here like staging, production etc


jobs:
    test:
        runs-on: ubuntu-latest # This is Container 

        # For every workflow step we specify step here 

        steps:
            # Step 1 : Check out the code from repository
            - name: Checkout the repository # This step clones the repository
              uses: actions/checkout@v2

            # Step 2 : Set up Python 3.8
            - name: Set up Python  # This step sets up Python 3.8
              uses: actions/setup-python@v2  # provided by github action 
              with:
                python-version: 3.8

            # Step 3 : Install dependencies
            - name: Install dependencies  # This step installs the required dependencies
              run: |
                python -m pip install --upgrade pip
                pip install -r requirements.txt

            # Step 4 : Run tests
            - name: Run tests  # This step runs the tests
              run: pytest 

            




